<?php
session_start();
include '../config/connection.php';

$currentYear = date('Y');
$currentMonth = date('m');
$currentDay = date('d');

// Fetch daily revenue data for the current year and month
$dailyRevenueQuery = "SELECT DAY(transaction_date) AS day, SUM(amount) AS total_revenue 
                      FROM revenue 
                      WHERE YEAR(transaction_date) = '$currentYear' 
                      AND MONTH(transaction_date) = '$currentMonth' 
                      AND transaction_type = 'debit'
                      GROUP BY DAY(transaction_date)";
$dailyRevenueResult = mysqli_query($conn, $dailyRevenueQuery);

// Check for query errors
if (!$dailyRevenueResult) {
    die("Database query failed: " . mysqli_error($conn));
}

// Initialize an array to hold the daily revenues
$dailyRevenue = array_fill(1, date('t', strtotime("$currentYear-$currentMonth-01")), 0);

// Populate the array with data from the query result
while ($row = mysqli_fetch_assoc($dailyRevenueResult)) {
    $dailyRevenue[$row['day']] = $row['total_revenue'];
}

$selectedDayRevenue = $dailyRevenue[$currentDay] ?? 0;
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Revenue Report</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
    </style>
</head>

<body>
    <div class="container mt-5">
        <h1>Revenue Report</h1>

        <!-- Filter Form -->
        <form id="filterForm" method="POST">
            <div class="row mb-3">
                <div class="col-md-4">
                    <label for="year" class="form-label">Select Year</label>
                    <select name="year" id="year" class="form-select" required>
                        <?php for ($i = 2020; $i <= date('Y'); $i++) {
                            $selected = ($i == $currentYear) ? 'selected' : '';
                            echo "<option value='$i' $selected>$i</option>";
                        } ?>
                    </select>
                </div>
                <div class="col-md-4">
                    <label for="month" class="form-label">Select Month</label>
                    <select name="month" id="month" class="form-select" required>
                        <?php for ($m = 1; $m <= 12; $m++) {
                            $selected = ($m == $currentMonth) ? 'selected' : '';
                            echo "<option value='$m' $selected>" . date("F", mktime(0, 0, 0, $m, 1)) . "</option>";
                        } ?>
                    </select>
                </div>
                <div class="col-md-4">
                    <div class="form-check">
                        <input type="checkbox" name="include_day" id="include_day" class="form-check-input">
                        <label for="include_day" class="form-check-label">Include Day</label>
                    </div>
                </div>
            </div>

            <div class="row mb-3" id="daySelection" style="display: none;">
                <div class="col-md-4">
                    <label for="day" class="form-label">Select Day</label>
                    <select name="day" id="day" class="form-select">
                        <!-- Options generated by PHP dynamically -->
                    </select>
                </div>
            </div>

            <button type="submit" class="btn btn-primary">Filter</button>
            <button type="button" class="btn btn-danger" id="generatePdfBtn">Download PDF</button>
        </form>

        <!-- Display Total Revenue -->
        <div class="mt-4" id="revenueDisplay">
            <h3>Total Revenue</h3>
            <p>₱<?php echo number_format($selectedDayRevenue, 2); ?></p>
        </div>

        <!-- Chart for daily revenue -->
        <canvas id="revenueChart" width="400" height="200"></canvas>
    </div>

    <script>
        // Show/Hide Day Selection
        document.getElementById('include_day').addEventListener('change', function () {
            document.getElementById('daySelection').style.display = this.checked ? 'block' : 'none';
        });

        // Handle form submission with AJAX
        document.getElementById('filterForm').addEventListener('submit', function (e) {
            e.preventDefault();
            const formData = new FormData(this);

            fetch('filter_revenue.php', {
                method: 'POST',
                body: formData,
            })
                .then(response => response.text())
                .then(data => {
                    document.getElementById('revenueDisplay').innerHTML = data;
                    updateChart(); // Update the chart based on new data
                })
                .catch(error => console.error('Error:', error));
        });

        // Update the chart
        function updateChart() {
            const ctx = document.getElementById('revenueChart').getContext('2d');
            const revenueData = <?php echo json_encode(array_values($dailyRevenue)); ?>; // Array of daily revenues
            const labels = Array.from({ length: revenueData.length }, (_, i) => i + 1); // Days of the month

            new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: labels,
                    datasets: [{
                        label: 'Daily Revenue',
                        data: revenueData,
                        backgroundColor: 'rgba(75, 192, 192, 0.2)',
                        borderColor: 'rgba(75, 192, 192, 1)',
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    }
                }
            });
        }

        // Handle PDF generation
        document.getElementById('generatePdfBtn').addEventListener('click', function () {
            const form = document.getElementById('filterForm');
            form.action = '?generate_pdf=1';
            form.submit();
        });
    </script>
</body>

</html>